swagger: '2.0'
info:
  description: |
    This UdaConnect API provices Connections related capabilities.
  version: 1.0.0
  title: UdaConnect - Connection API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: connection
  description: Connections of a person
- name: location
  description: Location datapoint
paths:
  /locations:
    post:
      tags:
      - location
      summary: Create a new Location
      operationId: addLocation
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: location
        description: Location to be created
        required: true
        schema:
          $ref: '#/definitions/Location'
      responses:
        200:
          description: Successful
        400:
          description: Invalid input
  /locations/{locationId}:
    get:
      tags:
      - location
      summary: Find Location by ID
      description: Returns a single Location
      operationId: getLocationById
      produces:
      - application/json
      parameters:
      - name: locationId
        in: path
        description: ID of Location to return
        required: true
        type: integer
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Location'
        400:
          description: Invalid ID supplied
        404:
          description: Location not found
  /connections:
    get:
      tags:
      - connection
      summary: Find Connections for the provided Person Id
      operationId: findConnections
      produces:
      - application/json
      parameters:
      - name: start_date
        in: query
        description: Lower bound of date range
        required: true
        type: string
        format: date
      - name: end_date
        in: query
        description: Upper bound of date range
        required: true
        type: string
        format: date
      - name: person_id
        in: query
        description: Unique ID for a given Person
        required: true
        type: integer
      - name: distance
        in: query
        description: Proximity to a given user in meters
        required: false
        default: 5
        type: integer
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Connection'
        400:
          description: Invalid tag value

definitions:
  Person:
    type: object
    required:
    - first_name
    - last_name
    - company_name
    properties:
      id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      company_name:
        type: string
    xml:
      name: Order
  Location:
    type: object
    required:
    - person_id
    - latitude
    - longitude
    properties:
      id:
        type: integer
      person_id:
        type: integer
      longitude:
        type: string
        format: float
      latitude:
        type: string
        format: float
      creation_time:
        type: string
        format: date-time
    xml:
      name: Location
  Connection:
    type: object
    required:
    - location
    - person
    properties:
      location:
        $ref: '#/definitions/Location'
      person:
        $ref: '#/definitions/Person'
    xml:
      name: Connection
host: localhost:30003
basePath: /api
schemes:
 - http